apiVersion: v1
kind: Secret
metadata:
  name: invoke-lambda-aws-creds
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.awsDefaultRegion | b64enc }}
